"""Поля для атрибутивной информации, их типы и комментарии"""

FIELDS = {
    'lands': {
        'name': 'lands',
        'desc': 'Земельные участки',
        'geom_types': ['MultiPolygon'],
        'unique': 'cad_number',
        'fields':[
            {'name': 'registration_number',
            'desc': 'Регистрационный номер выписки',
            'type': 'text'},
            {'name': 'date_formation',
            'desc': 'Дата формирования выписки',
            'type': 'timestamp with time zone'},
            {'name': 'cancel_date',
            'desc': 'Дата снятия с учета/регистрации',
            'type': 'timestamp with time zone'}, 
            {'name': 'address',
            'desc': 'Адрес (местоположение)',
            'type': 'text'}, 
            {'name': 'address_type',
            'desc': 'Тип адреса',
            'type': 'text'}, 
            {'name': 'subtype',
            'desc': 'Подтип',
            'type': 'text'}, 
            {'name': 'common_land_cad_number',
            'desc': 'Кадастровый номер единого землепользования',
            'type': 'text'},
            {'name': 'cad_number',
            'desc': 'Кадастровый номер',
            'type': 'text'}, 
            {'name': 'type',
            'desc': 'Тип',
            'type': 'text'}, 
            {'name': 'area_inaccuracy',
            'desc': 'Погрешность площади',
            'type': 'real'}, 
            {'name': 'area',
            'desc': 'Площадь',
            'type': 'real'}, 
            {'name': 'area_type',
            'desc': 'Тип площади',
            'type': 'text'}, 
            {'name': 'land_use_by_document',
            'desc': 'Вид разрешенного использования земельного участка по документу',
            'type': 'text'}, 
            {'name': 'land_use',
            'desc': 'Вид разрешенного использования земельного участка в соответствии с ранее использовавшимся классификатором',
            'type': 'text'}, 
            {'name': 'land_use_mer',
            'desc': 'Вид разрешенного использования земельного участка в соответствии с классификатором',
            'type': 'text'}
        ]
    },
    'quarters': {
        'name': 'quarters',
        'desc': 'Кадастровые кварталы',
        'geom_types': ['MultiPolygon'],
        'unique': 'cad_number',
        'fields':[
            {'name': 'date_formation',
            'desc': 'Дата формирования выписки',
            'type': 'timestamp with time zone'}, 
            {'name': 'cad_number',
            'desc': 'Кадастровый номер',
            'type': 'text'},
            {'name': 'area',
            'desc': 'Площадь',
            'type': 'real'}
        ]
    },
    'boundaries': {
        'name': 'boundaries',
        'desc': 'Муниципальные границы',
        'geom_types': ['MultiPolygon'],
        'unique': 'reg_numb_border',
        'fields':[
            {'name': 'registration_number',
            'desc': 'Регистрационный номер выписки',
            'type': 'text'}, 
            {'name': 'date_formation',
            'desc': 'Дата формирования выписки',
            'type': 'timestamp with time zone'},
            {'name': 'registration_date',
            'desc': 'Дата регистрации',
            'type': 'timestamp with time zone'},
            {'name': 'reg_numb_border',
            'desc': 'Регистрационный номер',
            'type': 'text'}, 
            {'name': 'cancel_date',
            'desc': 'Дата снятия с учета/регистрации',
            'type': 'timestamp with time zone'}, 
            {'name': 'type_boundary',
            'desc': 'Тип',
            'type': 'text'}
        ]
    },
    'zones': {
        'name': 'zones',
        'desc': 'Зоны и территории',
        'geom_types': ['MultiPolygon'],
        'unique': 'reg_numb_border',
        'fields':[
            {'name': 'registration_number',
            'desc': 'Регистрационный номер выписки',
            'type': 'text'}, 
            {'name': 'date_formation',
            'desc': 'Дата формирования выписки',
            'type': 'timestamp with time zone'},
            {'name': 'registration_date',
            'desc': 'Дата регистрации',
            'type': 'timestamp with time zone'},
            {'name': 'reg_numb_border',
            'desc': 'Регистрационный номер',
            'type': 'text'}, 
            {'name': 'type_boundary',
            'desc': 'Тип',
            'type': 'text'},
            {'name': 'type_zone',
            'desc': 'Тип',
            'type': 'text'},
            {'name': 'cancel_date',
            'desc': 'Дата снятия с учета/регистрации',
            'type': 'timestamp with time zone'}, 
            {'name': 'name_by_doc',
            'desc': 'Наименование по документу',
            'type': 'text'}
        ]
    },
    'coastlines': {
        'name': 'coastlines',
        'desc': 'Береговые линии',
        'geom_types': ['MultiLineString'],
        'unique': 'reg_numb_border',
        'fields':[
            {'name': 'registration_number',
            'desc': 'Регистрационный номер выписки',
            'type': 'text'}, 
            {'name': 'date_formation',
            'desc': 'Дата формирования выписки',
            'type': 'timestamp with time zone'},
            {'name': 'registration_date',
            'desc': 'Дата регистрации',
            'type': 'timestamp with time zone'},
            {'name': 'reg_numb_border',
            'desc': 'Регистрационный номер',
            'type': 'text'}, 
            {'name': 'cancel_date',
            'desc': 'Дата снятия с учета/регистрации',
            'type': 'timestamp with time zone'}, 
            {'name': 'water',
            'desc': 'Наименование водного объекта',
            'type': 'text'}
        ]
    }
}
